In [2]:
import numpy as np

##### Create a 4x4 matrix with values ranging from 0 to 3

In [27]:
a = np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
a[0,:4] = np.arange(4)
a[1,:4] = np.arange(4)
a[2,:4] = np.arange(4)
a[3,:4] = np.arange(4)
a

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

##### Create and array with shape of 4x4 and turn it into two arrays along the second axis.

In [32]:
b = np.arange(0,16).reshape((4,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
c = np.hsplit(b,2)
c

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]