In [1]:
import numpy as np

In [2]:
#Menambahkan data dalam array

x = np.arange(10)
print(x)
np.append(x, 10) #(nama array, data yang ditambahkan)

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
y = np.array([[1,2,3],[4,5,6]])
print(y)
np.append(y, [[2],[3]], axis=1) #(nama array, data, lokasi)

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3, 2],
       [4, 5, 6, 3]])

In [7]:
#concatenate (menggabungkan array)
x = [[0,1,3],[5,7,9]]
y = [[0,2,4],[6,8,10]]

arr1 = np.array(x)
arr2 = np.array(y)
z = np.concatenate((arr1, arr2), axis=0) #((array1, array2), lokasi)
y = np.concatenate((arr1, arr2), axis=1) #axis hanya 0 dan 1 karena 2 dimensi
print(arr1)
print()
print(arr2)
print()
print(z)
print()
print(y)

[[0 1 3]
 [5 7 9]]

[[ 0  2  4]
 [ 6  8 10]]

[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [8]:
#sorting (mengurutkan)
a = np.array([1,2,4,5,7,9,3])
np.sort(a)

array([1, 2, 3, 4, 5, 7, 9])

In [9]:
#mengubah dimensi
a = np.arange(2,11) #membuat array dengan batas
a.reshape(3,3) #mengubah dimensi dari 1 dimensi menjadi 2 dimensi (3 baris, 3 kolom)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [10]:
#menghapus data dalam array
c = np.array([[12,3,42,3],[4,3,6,2],[2,3,6,11]])
print(c)
print()
np.delete(c, (0,1), axis=1) #menghapus 2 kolom pertama (index dari 0) #array, (baris yang ingin dihapus)

[[12  3 42  3]
 [ 4  3  6  2]
 [ 2  3  6 11]]



array([[42,  3],
       [ 6,  2],
       [ 6, 11]])

In [11]:
#Melihat dimensi
x = np.array([[1,2,3,4],[4,2,3,1],[7,6,8,5]])
x.ndim

2

In [12]:
#melihat banyak data dalam array
x.size

12

In [13]:
#melihat bentuk array
x.shape #baris, kolom

(3, 4)

In [14]:
x = np.arange(2,11)
x.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [15]:
x = np.array([[0,1,3],[5,7,9]])
y = np.array([[0,2,4],[6,8,10]])
np.concatenate((x,y), axis=1)

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [16]:
#menambahkan axis dalam array
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [17]:
a2 = a[np.newaxis,:]
a2.shape

(1, 6)

In [18]:
a3 = a[:, np.newaxis]
a3.shape

(6, 1)

In [19]:
#expand
b = np.array([9,8,7,6])
b.shape

(4,)

In [20]:
b1 = np.expand_dims(b, axis=1)
b1.shape

(4, 1)

In [21]:
#indexing dan slicing
data = np.array([1,2,3,4,5,6])

In [22]:
data[1]

2

In [23]:
data[:3]

array([1, 2, 3])

In [24]:
data[1:]

array([2, 3, 4, 5, 6])

In [25]:
data[-2:]

array([5, 6])

In [27]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a[a<8]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
five_up = (a >= 5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

### Exercise 4

In [ ]:
a = np.zeros(10)
a[4] = 11
a

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b.reshape(3,2)

In [ ]:
c = np.ones((5,5))
c[1,1:4] = 0
c[2,1:4] = 0
c[3,1:4] = 0
c

In [ ]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2], # value ini
               [5, 2, 9],
               [1, 3, 3]]])
z[2,0]

##### batas exercixe

In [30]:
#Membuat array dari data yg tersedia
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [32]:
arr1 = a[3:8] #data ke 3 sampai 8
arr1

array([4, 5, 6, 7, 8])

In [33]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
a3 = np.array([[1,1],[2,2]])
a4 = np.array([[3,3],[4,4]])

In [34]:
#menggabungkan array secara horisontal
np.hstack((a1,a2,a3,a4))

array([[1, 1, 3, 3, 1, 1, 3, 3],
       [2, 2, 4, 4, 2, 2, 4, 4]])

In [35]:
#menggabungkan array secara vertikal
np.vstack((a1,a2,a3,a4))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [36]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
#membagi array secara horisontal
y = np.hsplit(x,2)
y

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [38]:
#membagi array secara vertikal
z = np.vsplit(x,2)
z

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [39]:
c = np.hsplit(x,(1,3))
c

[array([[ 1],
        [13]]),
 array([[ 2,  3],
        [14, 15]]),
 array([[ 4,  5,  6,  7,  8,  9, 10, 11, 12],
        [16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [40]:
a = np.array([1,2])
b = np.ones(2, dtype=int)

In [41]:
a

array([1, 2])

In [42]:
b

array([1, 1])

In [ ]:
a + b

In [ ]:
a - b

In [ ]:
a * b

In [ ]:
a / a

In [ ]:
a.sum()

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b.sum(axis=0)

In [ ]:
a * 3

#### Membuat file di numpy

In [ ]:
#save
a = np.array([1,2,3,4,5])
np.save('array', a) #(nama file, array)

In [ ]:
#load
b = np.load('array.npy')
b

In [ ]:
#save file txt atau csv
csv_arr = np.array([1,2,3,4,5,6,7,8])
np.savetxt('npArray.csv', csv_arr) #nama file, array

In [ ]:
#load data txt atau csv
np.loadtxt('npArray.csv')