In [1]:
#Import library numpy

import numpy as np

In [2]:
data = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
type(data)

list

In [3]:
#Membuat Array
arr = np.array(data) 
arr1 = np.array([4,5,6])
print(arr)
print()
print(arr1)

type(arr) #tipe data

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[4 5 6]


numpy.ndarray

In [4]:
#bentuk array
print(arr.shape) #4 baris, 3 kolom (2 dimensi)
print(arr1.shape) #3 kolom (1 dimensi)

#jumlah data dalam array
print(arr.size)

#tipe data
print(arr.dtype)

(4, 3)
(3,)
12
int32


In [5]:
#Mengubah tipe data
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[4,5,6]], dtype=float)
print(x)
print(x.dtype)
print()
print(y)
print(y.dtype)

[[1 2 3]
 [4 5 6]]
int32

[[1. 2. 3.]
 [4. 5. 6.]]
float64


In [6]:
#membuat matriks satu
arr = np.ones(5) #1 baris, 5 kolom
arr1 = np.ones((10,1)) #10 baris, 1 kolom
arr2 = np.ones((2,3,3)) #2 array, 3 kolom, 3 baris

print(arr)
print()
print(arr1)
print()
print(arr2)

[1. 1. 1. 1. 1.]

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [7]:
#membuat matriks zero
zero1 = np.zeros(10) #1 dimensi
zero2 = np.zeros((5,3)) #2 dimensi
zero3 = np.zeros((3,2,3)) #3 dimensi

print(zero1)
print()
print(zero2)
print()
print(zero3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [8]:
#mengubah isi matriks zero
arr4 = np.zeros((5,3))
for y in arr4:
    y+=2
print(arr4)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [10]:
#membuat arange
z = np.arange(15)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
#arange dengan batasan
x = np.arange(4,10) #mulai, akhir
x

array([4, 5, 6, 7, 8, 9])

In [12]:
#arange dengan batasan dan step
y = np.arange(1,11,2) #mulai, akhir, step
y

array([1, 3, 5, 7, 9])

In [15]:
#linspace
a = np.linspace(0,5,10) #nilai awal, nilai akhir, banyak data
a

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
#random
from numpy import random

#random uniform
random.rand(5,5) #kolom, baris

array([[0.63249575, 0.22191901, 0.06988799, 0.95397239, 0.7680308 ],
       [0.67684022, 0.61388406, 0.8543685 , 0.42170531, 0.36852467],
       [0.90300129, 0.65491347, 0.26403863, 0.60177382, 0.50446015],
       [0.88499453, 0.61903886, 0.92839427, 0.95494301, 0.28125514],
       [0.25950742, 0.17248285, 0.57393072, 0.3992401 , 0.83717626]])

In [17]:
#random nya ada nilai minusnya (normal random)
x = random.randn(5,5)
x

array([[-1.51028298,  0.76211834, -1.32938992,  0.14360188, -0.70275136],
       [ 1.42844548, -0.58775066,  0.04439588,  1.33151804,  0.28927948],
       [ 1.19411131, -0.82315418, -0.1701636 , -2.2915993 , -0.23075645],
       [-1.17909219,  1.36938454,  0.108513  , -1.05073026, -1.48641854],
       [-1.64659976,  2.10217329, -0.77174171, -0.88754037, -0.91579769]])

In [18]:
random.randint(9) #9 adalah batasan

5

In [19]:
random.randint(2,10, size=4) #start, stop, ukuran

array([4, 7, 7, 2])

In [23]:
random.randint(2,10, size=(4,2,2)) #start, stop, ukuran(array, baris, kolom)

array([[[9, 2],
        [6, 5]],

       [[8, 9],
        [6, 2]],

       [[4, 2],
        [5, 7]],

       [[3, 8],
        [9, 9]]])

In [21]:
random.randint(0,100,5) #start, stop, ukuran

array([53, 85, 68, 68, 81])

In [25]:
random.randint(0,100,(3,5)) #start, stop, ukuran (baris, kolom)

array([[91, 98,  3, 46, 11],
       [64, 83, 12,  2, 65],
       [68, 74, 86, 72, 60]])

In [26]:
x = np.linspace(1.5,5.5,30)
x

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])